In [2]:
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

1.12.1+cu102


## Introduction to Tensors

creating tensors

PyTorch tensors are created using 'torch.Tensor()'

In [4]:

# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix[1]

tensor([ 9, 10])

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

why random tensors?
Random tensors are important because they way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [17]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7622, 0.9714, 0.3119, 0.6829],
        [0.5915, 0.1018, 0.7842, 0.2003],
        [0.8963, 0.8370, 0.1845, 0.9077]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor ith similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour_channels, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [20]:
# create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.range()
one_to_ten = torch.range(start = 1,end = 10, step =1)
one_to_ten

/tmp/ipykernel_1280/1159606527.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(start = 1,end = 10, step =1)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big error you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - 
https://en.wikipedia.org/wiki/Precision_(computer_science)

In [27]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what data type is the tensor (eg. float 32)
                               device=None, # where to store the tensor (eg. cpu or gpu)
                               requires_grad=False) # will the autograd engine track the tensor for auto gradient calculations (for backpropagation)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [32]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to do et datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [33]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4627, 0.6034, 0.8866, 0.9448],
        [0.1872, 0.3829, 0.3167, 0.9606],
        [0.3228, 0.6184, 0.9460, 0.3396]])

In [34]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.4627, 0.6034, 0.8866, 0.9448],
        [0.1872, 0.3829, 0.3167, 0.9606],
        [0.3228, 0.6184, 0.9460, 0.3396]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensor (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [35]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [36]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [37]:
# Subtract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [38]:
# Try out PyTorch in-built function
print(torch.add(tensor,10))
print(torch.sub(tensor,10))
print(torch.mul(tensor,10))


tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])


### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication need to satisfy:
1. the **inner dimension** must match:
* `(3,2) @ (2,3)` will work (`Column of one matrix must be equal Row of the other matrix`)

In [45]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[2.5082, 2.3847, 2.4522, 2.6753, 1.9708, 2.8703, 1.6548, 2.0661, 2.7617,
         1.6252],
        [2.0328, 1.9905, 1.8964, 2.3905, 2.1592, 2.7785, 1.9444, 2.4184, 2.5579,
         1.4780],
        [1.4716, 1.4045, 2.1031, 2.0020, 1.1906, 2.4279, 1.5831, 1.6301, 2.1336,
         1.2529],
        [1.7368, 1.9109, 2.0295, 2.1360, 2.0949, 2.3867, 1.8170, 2.1728, 2.4704,
         1.1338],
        [2.1756, 1.6145, 2.5745, 2.4855, 1.5049, 2.6210, 1.5651, 1.8945, 2.4840,
         1.3368],
        [1.8722, 2.1659, 2.2015, 2.6784, 1.9043, 2.2597, 1.7790, 2.0008, 3.1747,
         1.3083],
        [3.1728, 3.2907, 3.0727, 3.7850, 2.4692, 4.2550, 2.9681, 2.5901, 3.9121,
         2.4321],
        [1.6669, 2.4801, 2.4759, 2.8440, 1.9962, 2.9526, 2.0473, 2.3789, 3.2149,
         1.6410],
        [2.7160, 2.4328, 1.8020, 2.5957, 2.4095, 2.8327, 1.8811, 2.3142, 2.8760,
         1.8271],
        [2.2418, 2.3504, 2.1922, 2.2668, 1.8527, 3.2082, 2.2161, 1.9639, 2.4325,
         1.5583]])

In [39]:
# Element wise multiplication
print(tensor,'*',tensor)
print(f'Equals:{tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [40]:
tensor @ tensor

tensor(14)

In [41]:
torch.matmul(tensor,tensor)

tensor(14)

In [42]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [43]:
%%time
value = 0
for i in range (len(tensor)):
    value += tensor[i]* tensor[i]

print(value)

tensor(14)
CPU times: user 1.14 ms, sys: 0 ns, total: 1.14 ms
Wall time: 968 µs


In [44]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 392 µs, sys: 0 ns, total: 392 µs
Wall time: 235 µs


tensor(14)

### One of the most Common errors in deep learning: shape errors

In [55]:
# Shapes for matrix multiplication (We have fixed the shape of our tensor_B using traspose method)
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B.T) # torch.mm is the same as torch.matmul (matrix multiplication)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [56]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [70]:
# Create a tensor
x= torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [58]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [59]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [63]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [64]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [71]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [72]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [73]:
x[0]

tensor(1)

In [74]:
# Find the position in tensor that has the maimum value with argmax()
x.argmax()

tensor(9)

In [75]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueeing tensors

* Reshaping - reshaping an input tensor to a defined shape
* view - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze -  removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions peruted (swapped) in a certain way

In [87]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [88]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [91]:
# change the view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [92]:
# Changing z changs x ( because a view of a tensor shared the same memory as the original tensor)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [103]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])