In [6]:
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

In [7]:
print(torch.__version__)

1.12.1+cu102


## Introduction to Tensors

creating tensors

PyTorch tensors are created using 'torch.Tensor()'

In [9]:

# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
# Get tensor back as python int
scalar.item()

7

In [12]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
# Matrix
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
matrix.ndim

2

In [17]:
matrix[1]

tensor([ 9, 10])

In [18]:
matrix.shape

torch.Size([2, 2])

In [21]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

why random tensors?
Random tensors are important because they way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [24]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0711, 0.4527, 0.0444, 0.8594],
        [0.5355, 0.3902, 0.8761, 0.3013],
        [0.4204, 0.1309, 0.4756, 0.3180]])

In [25]:
random_tensor.ndim

2

In [29]:
# Create a random tensor ith similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour_channels, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)