In [1]:
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

1.12.1+cu102


## Introduction to Tensors

creating tensors

PyTorch tensors are created using 'torch.Tensor()'

In [3]:

# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix[1]

tensor([ 9, 10])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

why random tensors?
Random tensors are important because they way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5929, 0.8632, 0.0447, 0.6898],
        [0.9263, 0.7657, 0.1168, 0.4631],
        [0.3005, 0.6586, 0.1845, 0.5530]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor ith similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour_channels, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [19]:
# create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
# Use torch.range()
one_to_ten = torch.range(start = 1,end = 10, step =1)
one_to_ten

/tmp/ipykernel_1528/1159606527.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(start = 1,end = 10, step =1)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big error you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - 
https://en.wikipedia.org/wiki/Precision_(computer_science)

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what data type is the tensor (eg. float 32)
                               device=None, # where to store the tensor (eg. cpu or gpu)
                               requires_grad=False) # will the autograd engine track the tensor for auto gradient calculations (for backpropagation)
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [31]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to do et datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [32]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6135, 0.3728, 0.8552, 0.1170],
        [0.8380, 0.0518, 0.6598, 0.3211],
        [0.7783, 0.3785, 0.3402, 0.3344]])

In [33]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.6135, 0.3728, 0.8552, 0.1170],
        [0.8380, 0.0518, 0.6598, 0.3211],
        [0.7783, 0.3785, 0.3402, 0.3344]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensor (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [34]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [36]:
# Subtract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Try out PyTorch in-built function
print(torch.add(tensor,10))
print(torch.sub(tensor,10))
print(torch.mul(tensor,10))


tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])


### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication need to satisfy:
1. the **inner dimension** must match:
* `(3,2) @ (2,3)` will work (`Column of one matrix must be equal Row of the other matrix`)

In [38]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[2.9131, 3.8318, 2.6044, 3.2276, 3.4639, 3.2807, 2.7044, 3.0710, 2.5592,
         3.1842],
        [1.6224, 2.2167, 1.5780, 1.9916, 1.9313, 1.3978, 2.2211, 2.1206, 1.6180,
         1.7057],
        [2.3488, 3.6949, 2.5541, 2.8727, 2.5506, 2.3331, 2.1289, 2.5498, 3.2170,
         2.5165],
        [2.5453, 3.8855, 2.3751, 3.0620, 2.9269, 2.7028, 2.0228, 3.0285, 3.4300,
         3.1018],
        [2.2299, 3.7050, 2.9412, 3.5703, 3.2137, 2.9473, 2.1288, 2.8137, 2.3769,
         2.7492],
        [2.3510, 3.2308, 2.8987, 2.8544, 2.5488, 2.5441, 2.5195, 2.1494, 1.9025,
         2.3363],
        [2.9847, 4.4711, 3.5613, 3.8737, 3.5540, 3.6941, 2.2600, 3.1816, 2.9876,
         3.1720],
        [2.1885, 3.4855, 2.7495, 2.5380, 2.6986, 2.6699, 2.3817, 3.0412, 2.3466,
         2.6953],
        [2.4596, 4.0852, 3.5921, 2.8839, 2.9092, 3.1040, 2.3941, 3.5012, 2.7365,
         3.0804],
        [1.6440, 2.7636, 2.1871, 2.2526, 2.1444, 2.2982, 1.1921, 2.0304, 1.8744,
         2.1654]])

In [39]:
# Element wise multiplication
print(tensor,'*',tensor)
print(f'Equals:{tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [40]:
tensor @ tensor

tensor(14)

In [41]:
torch.matmul(tensor,tensor)

tensor(14)

In [42]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [43]:
%%time
value = 0
for i in range (len(tensor)):
    value += tensor[i]* tensor[i]

print(value)

tensor(14)
CPU times: user 521 µs, sys: 223 µs, total: 744 µs
Wall time: 646 µs


In [44]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 31 µs, sys: 13 µs, total: 44 µs
Wall time: 78.2 µs


tensor(14)

### One of the most Common errors in deep learning: shape errors

In [45]:
# Shapes for matrix multiplication (We have fixed the shape of our tensor_B using traspose method)
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B.T) # torch.mm is the same as torch.matmul (matrix multiplication)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [46]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [47]:
# Create a tensor
x= torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [48]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [49]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [50]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [51]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [52]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [53]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [54]:
x[0]

tensor(1)

In [55]:
# Find the position in tensor that has the maimum value with argmax()
x.argmax()

tensor(9)

In [56]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueeing tensors

* Reshaping - reshaping an input tensor to a defined shape
* view - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze -  removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions peruted (swapped) in a certain way

In [57]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [58]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [59]:
# change the view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# Changing z changs x ( because a view of a tensor shared the same memory as the original tensor)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [61]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [62]:
 # torch.squeeze() - removes all the single dimensions from a target tensor
print(x_reshaped)
x_squeezed = x_reshaped.squeeze()
print(x_reshaped.squeeze())

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [63]:
# torch.unsqueeze() - adds a single dimension to a target tensor
x_squeezed.unsqueeze(dim=0)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [64]:
# torch.permute -  rearranges the dimensions of a target tensor in a specified order
x_original =  torch.rand(size = (224,224,3)) # [height, width, colour_channels]

#permute the original tensor to rearrange the axis ( or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->a, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f'New shape: {x_permuted.shape}')

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [65]:
# Create a tensor
import torch
x= torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [66]:
# Lets's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
# lets's index on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [68]:
# Let's index on the most inner bracker (last dimension)
x[0][2][2]

tensor(9)

In [69]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [70]:
x[:,:,2]

tensor([[3, 6, 9]])

In [71]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [72]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [73]:
# Get all values of the 0 dimension but only the index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [74]:
# Get index 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [75]:
# Index on x to return 9
x[:,2,2]

tensor([9])

In [76]:
# Index on x to return 3, 6, 9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy

NumPy is a popular scientifin Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [77]:
# NumPy array to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [78]:
array.dtype

dtype('float64')

In [79]:
tensor.dtype

torch.float32

In [80]:
torch.arange(1.0,8.0).dtype

torch.float32

In [81]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor
# tensor does not change

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [82]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [83]:
# Change the tensor, what happens to `numpy_tensor`
tensor  = tensor +1
tensor, numpy_tensor
# numpy_tensor does not change

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility ( trying to take random out of random )

In short how a neural network learns:

`Start with random numbers -> tensor operations -> update random numbers to try and make them better representations of data -> again -> again...`



To reduce the randomness in neural networks and PyTorch the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [84]:
# Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)


tensor([[0.6066, 0.9474, 0.7536, 0.2132],
        [0.2499, 0.6526, 0.8314, 0.0157],
        [0.5216, 0.6007, 0.4374, 0.1333]])
tensor([[0.3348, 0.6779, 0.0434, 0.2627],
        [0.5339, 0.8338, 0.5381, 0.5045],
        [0.2448, 0.3998, 0.5634, 0.9847]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [85]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

In [86]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


In [87]:
!gpu

/bin/bash: gpu: command not found


In [88]:
torch.cuda.is_available()

False

In [89]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [90]:
torch.cuda.device_count()

0

In [91]:
tensor=torch.rand(7,7)
tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

In [92]:
tensor.shape

torch.Size([7, 7])