In [6]:
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

In [7]:
print(torch.__version__)

1.12.1+cu102


## Introduction to Tensors

creating tensors

PyTorch tensors are created using 'torch.Tensor()'

In [9]:

# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
# Get tensor back as python int
scalar.item()

7

In [12]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
# Matrix
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
matrix.ndim

2

In [17]:
matrix[1]

tensor([ 9, 10])

In [18]:
matrix.shape

torch.Size([2, 2])

In [21]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

why random tensors?
Random tensors are important because they way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [24]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0711, 0.4527, 0.0444, 0.8594],
        [0.5355, 0.3902, 0.8761, 0.3013],
        [0.4204, 0.1309, 0.4756, 0.3180]])

In [25]:
random_tensor.ndim

2

In [29]:
# Create a random tensor ith similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour_channels, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [30]:
# create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype

torch.float32

In [34]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [42]:
# Use torch.range()
one_to_ten = torch.range(start = 1,end = 10, step =1)
one_to_ten

/tmp/ipykernel_39437/1159606527.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(start = 1,end = 10, step =1)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [43]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big error you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [49]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what data type is the tensor (eg. float 32)
                               device=None, # where to store the tensor (eg. cpu or gpu)
                               requires_grad=False) # will the autograd engine track the tensor for auto gradient calculations
float_32_tensor

tensor([3., 6., 9.])

In [45]:
float_32_tensor.dtype

torch.float32