In [2]:
import numpy as np

In [3]:
np.zeros(2)

array([0., 0.])

In [4]:
x1=np.zeros(1)

In [5]:
x1

array([0.])

In [24]:
defset = np.array(np.random.rand(1,10))

In [25]:
defset

array([[0.50769321, 0.70737154, 0.76001271, 0.12605035, 0.24061152,
        0.35790273, 0.15107608, 0.51131914, 0.0986171 , 0.47372045]])

In [8]:
defset = NULL

NameError: name 'NULL' is not defined

In [10]:
opp=np.array([1,2,3,4,5,6,7,8,9,10])

In [11]:
opp.append(11)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [12]:
opp.push(11)

AttributeError: 'numpy.ndarray' object has no attribute 'push'

In [13]:
opp[10]=11

IndexError: index 10 is out of bounds for axis 0 with size 10

In [14]:
opp.apend(11)

AttributeError: 'numpy.ndarray' object has no attribute 'apend'

In [16]:
print(opp[1]+opp[2])

5


In [17]:
print(opp)

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
np.array([1,2,3][4,5,6][7,8,9])

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/tmp/ipykernel_7192/3808638260.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  np.array([1,2,3][4,5,6][7,8,9])
/tmp/ipykernel_7192/3808638260.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  np.array([1,2,3][4,5,6][7,8,9])
/tmp/ipykernel_7192/3808638260.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  np.array([1,2,3][4,5,6][7,8,9])
/tmp/ipykernel_7192/3808638260.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  np.array([1,2,3][4,5,6][7,8,9])


TypeError: list indices must be integers or slices, not tuple

In [20]:
import pandas as pd


In [22]:
defnot = pd.DataFrame(
    np.random.rand(334,4)
)

In [23]:
defnot

0         1         2         3
0    0.633284  0.039587  0.198034  0.383129
1    0.686326  0.732532  0.357594  0.010809
2    0.669614  0.295207  0.152262  0.566522
3    0.873045  0.278114  0.420552  0.899045
4    0.559362  0.624995  0.789213  0.256148
..        ...       ...       ...       ...
329  0.937809  0.681842  0.533587  0.610396
330  0.719004  0.634847  0.303842  0.359460
331  0.855915  0.963187  0.929933  0.026858
332  0.750672  0.162751  0.467518  0.164350
333  0.102173  0.998865  0.915423  0.421890

[334 rows x 4 columns]

In [26]:
opp.loc()

AttributeError: 'numpy.ndarray' object has no attribute 'loc'

In [27]:
opp

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
defset.loc()

AttributeError: 'numpy.ndarray' object has no attribute 'loc'

In [29]:
defnot.loc()

In [32]:
print('hello word')

hello word


In [33]:
def sum(x,y):
    print(x+y)

In [34]:
sum(5,4)

9


In [35]:
import torch